version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels: ["dependencies", "automerge"]
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels: ["dependencies", "automerge"]
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types: ["minor", "patch"]
