name: Orchestrate
description: Run an autonomy task from mobile
labels: ["orchestrate"]
body:
  - type: dropdown
    id: task
    attributes:
      label: Task
      options: [bootstrap, deploy, smoke, heal, full-run, status]
    validations: { required: true }
  - type: input
    id: service
    attributes:
      label: Service (optional)
      placeholder: autonomy-api
  - type: textarea
    id: params
    attributes:
      label: Extra params (JSON)
      placeholder: '{"region":"us-east1"}'
