name: auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: dependabot/fetch-metadata@v2
        id: meta
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: Auto-approving Dependabot PR
      - uses: peter-evans/auto-merge@v3
        with:
          merge-method: squash
          commit-message: pull-request-title
          delete-branch: true

  automerge_label:
    if: contains(join(github.event.pull_request.labels.*.name, ','), 'automerge')
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/auto-merge@v3
        with:
          merge-method: squash
          commit-message: pull-request-title
          delete-branch: true
