name: Cloud Run Auto-Heal
on:
  schedule: [{ cron: '*/10 * * * *' }]
  workflow_dispatch: {}
permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  probe:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: infinity-x-one-swarm-system
      REGION: us-east1
      SERVICES: ai-gateway orchestrator memory-gateway
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: gha-deployer@infinity-x-one-swarm-system.iam.gserviceaccount.com
      - uses: google-github-actions/setup-gcloud@v3
      - name: Probe & open issue if unhealthy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          for svc in $SERVICES; do
            url=$(gcloud run services describe $svc --region $REGION --project $PROJECT_ID --format='value(status.url)')
            [ -z "$url" ] && continue
            code=$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 5 --max-time 10 "$url/health") || code=000
            if [ "$code" != "200" ]; then
              title="Auto-heal: $svc health $code"
              body="$svc at $url/health returned $code. Please investigate."
              gh issue create -t "$title" -b "$body" || true
            fi
          done
