name: ci-cd
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test-deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Auth to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: gha-deployer@infinity-x-one-swarm-system.iam.gserviceaccount.com
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
      - name: Install deps
        run: sudo apt-get update -y && sudo apt-get install -y jq
      - name: Unit tests & lint & security scan
        run: ./scripts/ci_checks.sh
      - name: Build images
        run: ./scripts/build_all.sh
      - name: Push images
        run: ./scripts/push_all.sh
      - name: Deploy services
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: ./scripts/deploy_all.sh
      - name: Post-deploy warmers
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: ./scripts/schedule_warmers.sh
