name: CI
on:
  pull_request:
  push:
    branches: [ main ]
permissions:
  id-token: write
  contents: read

jobs:
  python:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: services } }
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Lint & type-check
        run: |
          pipx install ruff mypy pytest
          find . -name requirements.txt -maxdepth 3 -print0 | xargs -0 -I {} bash -c 'pip install -r {}; true'
          ruff check .
          mypy --install-types --non-interactive || true
          pytest -q || echo 'No tests yet'

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Sanity build Dockerfiles
        run: |
          set -euo pipefail
          for svc in services/*; do
            [ -f "$svc/Dockerfile" ] || continue
            docker build -q $svc
          done
