name: ci

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Import smoke
        run: |
          python - << 'PY'
          import importlib
          import sys
          for m in ['app.main','app.store','app.worker']:
              importlib.import_module(m)
          print('import ok')
          PY
