name: secretless-env
on: [workflow_call]
permissions:
  id-token: write
  contents: read
jobs:
  inject:
    runs-on: ubuntu-24.04
    steps:
      - name: Auth to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: gha-deployer@infinity-x-one-swarm-system.iam.gserviceaccount.com
      - name: Load secrets from Secret Manager into env (ephemeral)
        id: sm
        run: |
          get_secret(){ gcloud secrets versions access latest --secret=$1; }
          echo "MY_API_KEY=$(get_secret MY_API_KEY)" >> $GITHUB_ENV
          echo "ANOTHER_TOKEN=$(get_secret ANOTHER_TOKEN)" >> $GITHUB_ENV
