name: Deploy to Vercel
on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Vercel deploy
        run: |
          npm i -g vercel
          vercel pull --yes --environment=production --token="${{ secrets.VERCEL_TOKEN }}"
          vercel build --prod --token="${{ secrets.VERCEL_TOKEN }}"
          vercel deploy --prebuilt --prod --token="${{ secrets.VERCEL_TOKEN }}"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
